<?php

return [
    'signatory' => [
        'name' => 'RISKY',
        'title' => 'HRD',
    ],

    'director' => [
        'name' => 'Ir. Labib Naufal Muttaqien S.Kom.',
        'title' => 'Direktur CV. Toedjoe Sinar Group',
    ],

    'list' => [
        1 => ['name' => 'SUGIANTO', 'email' => 'sugynuansafx@gmail.com', 'jabatan' => 'Kepala Maintenance Operator', 'alamat' => 'Samarinda', 'tgl_masuk' => '2015-08-01'],
        2 => ['name' => 'MUHAMMAD NOR DIANSYAH', 'email' => 'Nurdinzds@gmail.com', 'jabatan' => 'Kepala Operator Indoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2015-08-01'],
        3 => ['name' => 'SRI WAHYUNI', 'email' => 'uyung109@gmail.com', 'jabatan' => 'Kepala Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2015-08-01'],
        4 => ['name' => 'FELIX OCTAVIAN MAHENDRA', 'email' => 'mahendrafelix@gmail.com', 'jabatan' => 'Kepala Admin & Personalia', 'alamat' => 'Samarinda', 'tgl_masuk' => '2017-08-01'],
        5 => ['name' => 'SUTIKNO', 'email' => 'sutiknokosong7@gmail.com', 'jabatan' => 'Kepala Finishing', 'alamat' => 'Samarinda', 'tgl_masuk' => '2017-08-01'],
        6 => ['name' => 'DEKI SAPUTRA', 'email' => 'pandabakpao10@gmail.com', 'jabatan' => 'Kepala TEXTILE/DTF', 'alamat' => 'Samarinda', 'tgl_masuk' => '2017-10-02'],
        7 => ['name' => 'ISMAIL', 'email' => 'mail87.ismail@gmail.com', 'jabatan' => 'Asisten Operator Indoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2018-05-01'],
        8 => ['name' => 'MUHAJIR', 'email' => 'ajirgalaxy@gmail.com', 'jabatan' => 'Kepala Laser/UV/DTF', 'alamat' => 'Samarinda', 'tgl_masuk' => '2019-05-22'],
        9 => ['name' => 'MOHAMMAD NADZORI', 'email' => 'm.nadzory@gmail.com', 'jabatan' => 'Asisten Operator Indoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2019-11-22'],
        10 => ['name' => 'SANDRA WIDIYA', 'email' => 'sandrawdy40@gmail.com', 'jabatan' => 'Design & Kepala Kasir', 'alamat' => 'Samarinda', 'tgl_masuk' => '2020-08-01'],
        11 => ['name' => 'MUHAMMAD IHSANUL AKMAL', 'email' => 'muhammadihsanulakmal.18@gmail.com', 'jabatan' => 'Kepala Operator Digital A3', 'alamat' => 'Samarinda', 'tgl_masuk' => '2020-08-01'],
        12 => ['name' => 'AGUNG DWI RAHMADI', 'email' => 'agungdr463@gmail.com', 'jabatan' => 'Asisten Operator Indoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2020-09-01'],
        13 => ['name' => 'ANJASMARA RAMADHAN', 'email' => 'anjasoedinson@gmail.com', 'jabatan' => 'Asisten Digital A3', 'alamat' => 'Samarinda', 'tgl_masuk' => '2021-01-01'],
        14 => ['name' => 'FANI NOR HAMDANI', 'email' => 'faninh41@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2021-11-28'],
        15 => ['name' => 'IKE TRIWAHYUNI', 'email' => 'triwahyuniike50@gmail.com', 'jabatan' => 'Asisten Desainer & Kasir', 'alamat' => 'Samarinda', 'tgl_masuk' => '2022-07-01'],
        16 => ['name' => 'AHMAD RIDHANI', 'email' => 'ahmadridhani87@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2022-07-01'],
        17 => ['name' => 'MUHAMMAD FERDIAN', 'email' => 'muhammadferdian0451@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2022-08-01'],
        18 => ['name' => 'ZUASA RAZZAK GHANI', 'email' => 'zuasarazak1@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2022-09-01'],
        19 => ['name' => 'ARYA GYMNAS FATAHILAH', 'email' => 'aryagymnasf25@gmail.com', 'jabatan' => 'Asisten Textile/DTF', 'alamat' => 'Samarinda', 'tgl_masuk' => '2022-10-01'],
        20 => ['name' => 'RISNUR RAMADHAN', 'email' => 'ramadhanrisnur@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2023-05-20'],
        21 => ['name' => 'MAULANA RUMI DAENG RINGGI', 'email' => 'itsmeschweigen@gmail.com', 'jabatan' => 'Asisten Operator Outdoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2023-05-15'],
        22 => ['name' => 'MUHAMMAD FAUZAN', 'email' => 'm.f4uzan12477@gmail.com', 'jabatan' => 'Asisten Operator Outdoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2023-06-06'],
        23 => ['name' => 'NUR RINO AIDUL FADLI', 'email' => 'rinofadlipratama04@gmail.com', 'jabatan' => 'Kepala Konten & Marketing', 'alamat' => 'Samarinda', 'tgl_masuk' => '2023-06-26'],
        24 => ['name' => 'RUSMONO HADI', 'email' => 'Rusmonohady@gmail.com', 'jabatan' => 'Asisten Operator Outdoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2023-08-09'],
        25 => ['name' => 'MUHAMMAD YUSRIL ARIMULIA', 'email' => 'sayangyusril22@gmail.com', 'jabatan' => 'Kepala Pengambilan', 'alamat' => 'Samarinda', 'tgl_masuk' => '2023-12-15'],
        26 => ['name' => 'MUHAMMAD ZIQI FARHAN', 'email' => 'ziqigustinaldi@gmail.com', 'jabatan' => 'Asisten Operator Outdoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2024-01-29'],
        27 => ['name' => 'RISKI NUR HALIS', 'email' => 'riskinurhalis11@gmail.com', 'jabatan' => 'Asisten Laser/UV/DTF', 'alamat' => 'Samarinda', 'tgl_masuk' => '2024-02-02'],
        28 => ['name' => 'AHMAT CAHYADI', 'email' => 'cahyadiahmat99@gmail.com', 'jabatan' => 'Asisten Pengambilan', 'alamat' => 'Samarinda', 'tgl_masuk' => '2024-05-01'],
        29 => ['name' => 'MUHAMMAD RAWINDRA FADILAH', 'email' => 'Fadilfira31@gmail.com', 'jabatan' => 'Asisten Digital A3', 'alamat' => 'Samarinda', 'tgl_masuk' => '2024-05-20'],
        30 => ['name' => 'MUHAMMAD KAMAL', 'email' => 'raeelyy21@gmail.com', 'jabatan' => 'Asisten Merchandise', 'alamat' => 'Samarinda', 'tgl_masuk' => '2024-06-03'],
        31 => ['name' => 'MUHAMMAD ILHAM NAZHIF', 'email' => 'm.ilhamnazhif23@gmail.com', 'jabatan' => 'Asisten Operator Outdoor', 'alamat' => 'Samarinda', 'tgl_masuk' => '2024-09-16'],
        32 => ['name' => 'AYU NANDA WULANDARI', 'email' => 'ayunandawul15@gmail.com', 'jabatan' => 'Desainer Admin Online', 'alamat' => 'Samarinda', 'tgl_masuk' => '2024-12-23'],
        33 => ['name' => 'ATHASYAHRI SYAWAL FAHREZY', 'email' => 'athafarez2412@gmail.com', 'jabatan' => 'Website', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-01-01'],
        34 => ['name' => 'DAVI JUNIAR', 'email' => 'juniardavi5@gmail.com', 'jabatan' => 'Asisten Digital A3', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-02-10'],
        35 => ['name' => 'MUHAMMAD ZIKRI FARHAN', 'email' => 'zikrifarhan05@gmail.com', 'jabatan' => 'Asisten Indoor Cutting', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-05-03'],
        36 => ['name' => 'MUHAMMAD NAUFAL PRIMANANDA', 'email' => 'az5733356@gmail.com', 'jabatan' => 'Asisten Pengambilan', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-05-12'],
        37 => ['name' => 'MUHAMMAD ZAKI MUBARAK', 'email' => 'zm0700910@gmail.com', 'jabatan' => 'Asisten Pengambilan', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-05-13'],
        38 => ['name' => "MUHAMMAD RAFI'I", 'email' => 'rfyxyz@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-05-04'],
        39 => ['name' => 'IMROATUS SHOLIKHA', 'email' => 'imroatussholikha8597@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-10-27'],
        40 => ['name' => 'EFIN QOID AMALLUDIN', 'email' => 'efinqoidamalludin@gmail.com', 'jabatan' => 'Asisten Desainer', 'alamat' => 'Samarinda', 'tgl_masuk' => '2025-11-03'],
    ],
];
